name: Electron CI
 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
 
jobs:
  build:
    runs-on: ${{ matrix.os }}
 
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
 
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22' 
 
    - name: Install dependencies
      run: npm ci 
 
    - name: Rebuild native modules for Electron
      run: npm run rebuild 
 
    - name: Build Electron app
      run: npm run build 
